[2022-08-11 03:22:31,765] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr1 manual__2022-08-11T03:22:29.449281+00:00 [queued]>
[2022-08-11 03:22:31,785] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: craw.cr1 manual__2022-08-11T03:22:29.449281+00:00 [queued]>
[2022-08-11 03:22:31,785] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 03:22:31,786] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-11 03:22:31,787] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 03:22:31,814] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cr1> on 2022-08-11 03:22:29.449281+00:00
[2022-08-11 03:22:31,824] {standard_task_runner.py:52} INFO - Started process 4094 to run task
[2022-08-11 03:22:31,829] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'craw', 'cr1', 'manual__2022-08-11T03:22:29.449281+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/newtest.py', '--cfg-path', '/tmp/tmpng_oqnuu', '--error-file', '/tmp/tmpbl9ck2jx']
[2022-08-11 03:22:31,832] {standard_task_runner.py:80} INFO - Job 57: Subtask cr1
[2022-08-11 03:22:31,948] {task_command.py:371} INFO - Running <TaskInstance: craw.cr1 manual__2022-08-11T03:22:29.449281+00:00 [running]> on host d59619969b18
[2022-08-11 03:22:32,082] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=craw
AIRFLOW_CTX_TASK_ID=cr1
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T03:22:29.449281+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-11T03:22:29.449281+00:00
[2022-08-11 03:22:32,085] {logger.py:11} INFO - ====== WebDriver manager ======
[2022-08-11 03:22:32,238] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome 104.0.5112
[2022-08-11 03:22:33,081] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/104.0.5112/chromedriver] found in cache
[2022-08-11 03:26:03,437] {logging_mixin.py:115} INFO - 1
[2022-08-11 03:28:54,650] {logging_mixin.py:115} INFO - 2
[2022-08-11 03:31:42,914] {logging_mixin.py:115} INFO - 3
[2022-08-11 03:31:43,080] {python.py:173} INFO - Done. Returned value was: None
[2022-08-11 03:31:43,106] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=craw, task_id=cr1, execution_date=20220811T032229, start_date=20220811T032231, end_date=20220811T033143
[2022-08-11 03:31:43,169] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-11 03:31:43,215] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
