[2022-08-10 06:11:28,506] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fuck.fucking manual__2022-08-10T05:19:17.526661+00:00 [None]>
[2022-08-10 06:11:28,525] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: fuck.fucking manual__2022-08-10T05:19:17.526661+00:00 [None]>
[2022-08-10 06:11:28,526] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-10 06:11:28,526] {taskinstance.py:1377} INFO - Starting attempt 4 of 4
[2022-08-10 06:11:28,527] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-10 06:11:28,552] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fucking> on 2022-08-10 05:19:17.526661+00:00
[2022-08-10 06:11:28,558] {standard_task_runner.py:52} INFO - Started process 376 to run task
[2022-08-10 06:11:28,564] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'fuck', 'fucking', 'manual__2022-08-10T05:19:17.526661+00:00', '--job-id', '19', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/tmp.py', '--cfg-path', '/tmp/tmpu0d6ms7j', '--error-file', '/tmp/tmpqz_omevj']
[2022-08-10 06:11:28,565] {standard_task_runner.py:80} INFO - Job 19: Subtask fucking
[2022-08-10 06:11:28,712] {task_command.py:371} INFO - Running <TaskInstance: fuck.fucking manual__2022-08-10T05:19:17.526661+00:00 [running]> on host 7b89d46fe45e
[2022-08-10 06:11:28,843] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fuck
AIRFLOW_CTX_TASK_ID=fucking
AIRFLOW_CTX_EXECUTION_DATE=2022-08-10T05:19:17.526661+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-10T05:19:17.526661+00:00
[2022-08-10 06:11:28,845] {logger.py:11} INFO - ====== WebDriver manager ======
[2022-08-10 06:11:29,069] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome 104.0.5112
[2022-08-10 06:11:29,497] {logger.py:11} INFO - Driver [/home/***/.wdm/drivers/chromedriver/linux64/104.0.5112/chromedriver] found in cache
[2022-08-10 06:11:34,128] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tmp.py", line 26, in ttt
    sleep(5)
NameError: name 'sleep' is not defined
[2022-08-10 06:11:34,161] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=fuck, task_id=fucking, execution_date=20220810T051917, start_date=20220810T061128, end_date=20220810T061134
[2022-08-10 06:11:34,191] {standard_task_runner.py:97} ERROR - Failed to execute job 19 for task fucking (name 'sleep' is not defined; 376)
[2022-08-10 06:11:34,236] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-10 06:11:34,282] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-10 06:11:34,313] {dagrun.py:549} ERROR - Marking run <DagRun fuck @ 2022-08-10 05:19:17.526661+00:00: manual__2022-08-10T05:19:17.526661+00:00, externally triggered: True> failed
[2022-08-10 06:11:34,314] {dagrun.py:624} INFO - DagRun Finished: dag_id=fuck, execution_date=2022-08-10 05:19:17.526661+00:00, run_id=manual__2022-08-10T05:19:17.526661+00:00, run_start_date=None, run_end_date=2022-08-10 06:11:34.314863+00:00, run_duration=None, state=failed, external_trigger=True, run_type=manual, data_interval_start=2022-08-09 00:00:00+00:00, data_interval_end=2022-08-10 00:00:00+00:00, dag_hash=9059b4adf9ac79c8a8346bf64e0f2f15
[2022-08-10 06:11:34,315] {dagrun.py:795} WARNING - Failed to record duration of <DagRun fuck @ 2022-08-10 05:19:17.526661+00:00: manual__2022-08-10T05:19:17.526661+00:00, externally triggered: True>: start_date is not set.
